### ISSUE TITLE
Attach

### ISSUE THREAD

**Issue by SimonHLMC** [tripleslash/wowscout#2]
BOOL CALLBACK windowEnumFunc(HWND hwnd, LPARAM lparam)
seems not to work when window titel ist "WORLD OF WARCRAFT"

**Comment by tripleslash** [comment]
Sorry, what do you mean? Isn't the game title in Classic, TBC, Wrath and Cata always "World of Warcraft"?

**Comment by SimonHLMC** [comment]
Idk but my classic client is "WORLD OF WARCRAFT"
