### ISSUE TITLE
a working stdin for the project? Otherwise open source?

### ISSUE THREAD

**Issue by Entzprot** [tripleslash/wowscout#4]
I am trying to write some scripts to automate some packet sending with the tool which I love!

However i am in no way able to emulate any keystrokes or anything alike. Could you add the possibilty please :D

**Comment by budasnorbi** [comment]
Hey, i be able to controll the loader.exe with node.js.
This a little piece of my code:
_(Btw you have to launch your terminal as an administrator in order to execute the script properly)_
With the \n i did an enter keystroke i guess
```javascript
const sniffer = require("child_process").spawn("./wowscout/loader.exe");
sniffer.stdout.on("data", async (data) => {
  const text = data.toString();

  if (text.includes("Done. Type in exit to stop the program.")) {
    sniffer.stdin.write("blacklist all \n");
  }
});
```

**Comment by tripleslash** [comment]
The source code for the loader is in the repository so you can just write your own and directly call commands via the public API

https://github.com/tripleslash/wowscout/blob/master/additional/loader.cpp

and the public API header

https://github.com/tripleslash/wowscout/blob/master/additional/scout.h
