### ISSUE TITLE
blocking a package results in "enqueuing"

### ISSUE THREAD

**Issue by m0use0ver** [tripleslash/wowscout#5]
hey there

I am currently messing around with the modifications, and have stumled over the following issue. When I observe sent packages which I want to prevent, I tried to use the instructed command:
block 0xExample

When the blocked package is called during one of my actions, the package is still being sent.

Nvm, blocking packages works fine. There was a second package I overlooked.

**Comment by tripleslash** [comment]
When a packet is ```block```-ed wowscout will put it into its internal packet queue, just like using ```send queue```. You can then decide to send all blocked packets later, by using the ```send```-command with no arguments. If you dont want to send them but queue different packets, then use the ```flush```-command which will clear the packet queue.
